name: GitHub Metrics

on:
  schedule:
    - cron: "0 3 * * *" # todo dia Ã s 03:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: IsraelHamdan
          template: classic
          theme: midnight-purple

          base: header, activity, community, repositories

          plugins: |
            languages
            commits
            habits

          plugins_languages: yes
          plugins_languages_limit: 8
          plugins_languages_threshold: 0%

          plugins_commits: yes
          plugins_habits: yes
